main: net.mcwarlords.wlplugin.WlPlugin
name: wlplugin
version: 1.0.0
api-version: 1.16
commands:
  wlchat:
    description: Interactions relating to the wlchat module. Type /wlchat help for more info
    usage: /<command> <subcommand> [args...]
    permission: wlplugin.wlchat
    aliases: [wc, wlc]
  wlplot:
    description: Interactions relating to the wlplot module. Type /wlplot help for more info
    usage: /<command> <subcommand> [args...]
    permission: wlplugin.wlplot
    aliases: [wp, wlp]
  wlgame:
    description: Interactions relating to the wlgame module. Type /wlgame help for more info
    usage: /<command> <subcommand> [args...]
    permission: wlplugin.wlgame
    aliases: [wg, wlg]
  wlschema:
    description: Interactions relating to the wlschema module. Type /wlschema help for more info
    usage: /<command> <subcommand> [args...]
    aliases: [ws, wls]
  wlcode:
    description: Interactions relating to the wlcode module. Type /wlcode help for more info
    usage: /<command> <subcommand> [args...]
    aliases: [wco, wlco]