main: net.mcwarlords.wlplugin.WlPlugin
name: wlplugin
version: 1.0.0
api-version: 1.16
commands:
  wlchat:
    description: Interactions relating to the wlchat module. Type /wlchat help for more info
    usage: /<command> <subcommand> [args...]
    permission: wlplugin.wlchat
    aliases: [wc, wlc]
  wlplot:
    description: Interactions relating to the wlplot module. Type /wlplot help for more info
    usage: /<command> <subcommand> [args...]
    permission: wlplugin.wlplot
    aliases: [wp, wlp]
  wlgame:
    description: Interactions relating to the wlgame module. Type /wlgame help for more info
    usage: /<command> <subcommand> [args...]
    permission: wlplugin.wlgame
    aliases: [wg, wlg]
  wlschema:
    description: Interactions relating to the wlschema module. Type /wlschema help for more info
    usage: /<command> <subcommand> [args...]
    permission: wlplugin.wlschema
    aliases: [ws, wls]
  wlshell:
    description: Executes wlshell commands
    usage: /<command> <shell command>
    permission: wlplugin.wlshell
    aliases: [w$, wl$, $]